name: Deploy Simple CI/CD

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: ap-northeast-1
  ECS_SERVICE: simple-cicd-service
  ECS_CLUSTER: simple-cicd-cluster
  ECS_TASK_DEFINITION: .aws/task-definition.json

permissions:
  contents: read

# Web Container Build/Test
## Get Source
## Build/test
## Docker Image Build
## Login AWS
## Push image to ECR

jobs:
  web-test-build-image:
    name: Web Container -Test and Build
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    defaults:
      run:
        working-directory: web
    
    steps:
      - uses: actions/checkout@v3

      - name: Build an Image and Run Tests
        run:
          docker image build --target production -t temp_web_image_name:latest --build-arg REACT_APP_SERVER=/api .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credential@v1
        with:
          aws-access-key-id: $ {{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: $ {{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

# api Container Build/Test
## Get Source
## Build/test
## Docker Image Build
## Login AWS
## Push image to ECR


# Deploy
## Get Source
## Login AWS
## Edit Task Definition
## Deploy

